### ISSUE TITLE
Crypto missing large image

### ISSUE THREAD

**Issue by benolot** [overtrack-gg/overtrack-web-2#2]
See: https://apex.overtrack.gg/game/thesast/2019-10-14-19-12-yRkDhB

Crypto is missing from the large image section in the bottom where it shows the three

**Comment by synap5e** [comment]
The source image to use is https://media.contentapi.ea.com/content/dam/apex-legends/images/2019/01/legends-character-tiles/apex-grid-tile-legends-crypto.png.adapt.crop16x9.png
Although I remove the red bar for the site.

A higher quality image is at https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-crypto-xl.jpg.adapt.1920w.jpg, but this would need more work and I think the linked is of the correct quality.

**Comment by synap5e** [comment]
Fixed in 04be78b
