### ISSUE TITLE
Game summary cards can be too wide if their row contains less than the above row

### ISSUE THREAD

**Issue by synap5e** [overtrack-gg/overtrack-web-2#6]
![image](https://user-images.githubusercontent.com/2515062/74518427-b041e600-4f78-11ea-841e-60028e9ed77e.png)

The last 2 games should be equal width to all the others, with empty space on the right.
I'm not familiar with flex-box, and am currently stuck on how to fix this without ugly hacks.

Files of interest:
- https://github.com/overtrack-gg/overtrack-web-2/blob/master/overtrack_web/static/scss/overwatch/games_list.scss
- https://github.com/overtrack-gg/overtrack-web-2/blob/master/overtrack_web/templates/overwatch/games_list/sessions_page.html (card-deck container)
- https://github.com/overtrack-gg/overtrack-web-2/blob/master/overtrack_web/templates/overwatch/games_list/game_card.html (each card)

**Comment by LeSqueed** [comment]
Noting down what I did in the developer tools of chrome to get a decent looking page. Noting it down for future reference. I have literally never worked with scss. Will have to get this running on a dev. environment on my own machine to see how to actually apply this code to the source to reflect this change.

From: 
`@media (min-width: 576px)
.card-deck .card {
    flex: 1 0 0%;
    margin-right: 15px;
    margin-bottom: 0;
    margin-left: 15px;
}`

To: 
`@media (min-width: 576px)
.card-deck .card {
    flex: 0 0 0%;
    margin-right: 15px;
    margin-bottom: 0;
    margin-left: 15px;
}`

From: 
`.@media (min-width: 576px)
.card-deck {
    display: flex;
    flex-flow: row wrap;
    margin-right: -15px;
    margin-left: -15px;
}`

To:
`@media (min-width: 576px)
.card-deck {
    display: flex;
    justify-content: center;
    flex-flow: row wrap;
    margin-right: -15px;
    margin-left: -15px;
}`

What this does is change the property of the flexbox to not allow items to grow and center flexboxes to avoid them being weirdly positioned to the left or right.

![image](https://user-images.githubusercontent.com/7735143/74559987-e4f87200-4f65-11ea-8166-7b59a5f14e67.png)

**Comment by synap5e** [comment]
hmm I'm a big fan of the growing, and generally in favor of the left alignment too.
I think this makes it work better on narrow screens especially.

I did come up with an alternate fix which achieves this though.
By adding 3 height=0 elements after the last it ensures consistent sizing and left alignment.
```html
{% for i in range(3) %}
<div class="card game-summary" style="height: 0;opacity: 0;"></div>
{% endfor %}
```
![image](https://user-images.githubusercontent.com/2515062/74568365-b073cd00-4fdc-11ea-9ad0-091e9717061c.png)

A (simple) pure CSS fix would be ideal, but if that doesn't prove possible I think I'll go for the invisible extra cards.

**Comment by JWSenteney** [comment]
I think you just need to control the width of the cards.  You're using bootstrap right?  So basically they need to have a width of 4 (using bootstraps 12 unit width grids).  See this example in the bootstrap documentation:  https://getbootstrap.com/docs/4.4/layout/grid/#row-columns

Edit: Actually that particular example doesn't use the 12 unit scale I was thinking of, but it still looks like what you need.  It allows you to set responsive breakpoints too.

**Comment by synap5e** [comment]
This is using card + card-deck rather than the grid system, unless I can use both at the same time. I'll check.

**Comment by JWSenteney** [comment]
There is a grid card system that might be more what you're looking for.

https://getbootstrap.com/docs/4.4/components/card/#grid-cards

**Comment by synap5e** [comment]
Yeah trying to add the grid system overrides the flex system that's going on here and prevents them from growing to fit the space. Grid works on cards when the cards are only ever one width, but I want to keep the flex-grow behavior. 

I think it would be possible to achieve with a whole log of `@media` and conditional `max-width: X%`s (basically implementing the grid system) but because the flex already uses max-width to work it's not simple to get the two to play nicely.

**Comment by synap5e** [comment]
If someone can solve this in another way that keeps it consistent with current behavior (i.e as of d3e6a9a), or has an argument for why it should be another way then I could accept that, but otherwise I'm going to go with this quickfix and work on new features 😝
